# Generated by Django 6.0.5 on 2026-09-27 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_category_user_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='savings_goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
